set_property SRC_FILE_INFO {cfile:{C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/constrs_1/new/const1.xdc} rfile:../../../MIPI_loopback_2-5g.srcs/constrs_1/new/const1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXACTIVEHS]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[2]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[3]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[4]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[5]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[6]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[7]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_ENABLE]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXREQUESTHS]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXVALIDHS]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXACTIVEHS]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXACTIVEHS]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXVALIDHS]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[0]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[1]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[2]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[3]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[4]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[5]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[6]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[7]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXACTIVEHS]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXVALIDHS]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[0]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[1]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[2]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[3]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[4]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[5]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[6]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[7]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx66_hssio_i/inst/top_inst/clk_rst_top_inst/clk_scheme_inst/pll0_clkout0_out]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx66_clock_module_support_i/bd_7e2a_mipi_dphy_0_0_clock_module_tx_i/inst/mmcm_clk_out1]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW MEDIUM [get_ports rxbyteclkhs_0]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports rxbyteclkhs_0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL12 [get_ports rxbyteclkhs_0]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_0]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports rxbyteclkhs_0]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD POD12 [get_ports rxbyteclkhs_cnts_out_0]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_cnts_out_0]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports rxbyteclkhs_cnts_out_0]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD HSTL_I_12 [get_ports rxbyteclkhs_1]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_1]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports clk_out_0]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_STOPSTATE]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_STOPSTATE]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_STOPSTATE]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_STOPSTATE]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx67_hssio_i/inst/top_inst/clk_rst_top_inst/clk_scheme_inst/pll0_clkout0_out]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[0]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[1]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[2]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[3]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[4]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[5]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[6]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[7]}]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_ENABLE]]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXREQUESTHS]]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rx_div4_clk]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[7]}]]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[7]}]]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXACTIVEHS]]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXACTIVEHS]]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXVALIDHS]]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXACTIVEHS]]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXVALIDHS]]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXACTIVEHS]]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXVALIDHS]]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/clk_wiz_0/inst/dphy]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_STOPSTATE]]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_STOPSTATE]]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_STOPSTATE]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_STOPSTATE]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
