set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_ENABLE]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXREQUESTHS]





connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]

set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXVALIDHS]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXVALIDHS]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXVALIDHS]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[7]}]

set_property IOSTANDARD MIPI_DPHY_DCI [get_ports mipi_phy_if_clk_p]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_data_p[3]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_data_p[2]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_data_p[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {mipi_phy_if_data_p[0]}]
connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx66_hssio_i/inst/top_inst/clk_rst_top_inst/clk_scheme_inst/pll0_clkout0_out]]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx66_clock_module_support_i/bd_7e2a_mipi_dphy_0_0_clock_module_tx_i/inst/mmcm_clk_out1]]


set_property SLEW MEDIUM [get_ports rxbyteclkhs_0]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports rxbyteclkhs_0]
set_property IOSTANDARD SSTL12 [get_ports rxbyteclkhs_0]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_0]
set_property OFFCHIP_TERM NONE [get_ports rxbyteclkhs_0]

set_property IOSTANDARD POD12 [get_ports rxbyteclkhs_cnts_out_0]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_cnts_out_0]

set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports rxbyteclkhs_cnts_out_0]

set_property IOSTANDARD HSTL_I_12 [get_ports rxbyteclkhs_1]
set_property PACKAGE_PIN K23 [get_ports rxbyteclkhs_1]

set_property IOSTANDARD HSTL_I_12 [get_ports clk_out_0]
set_property PACKAGE_PIN K23 [get_ports clk_out_0]

connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]


set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_STOPSTATE]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_STOPSTATE]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_STOPSTATE]
set_property MARK_DEBUG true [get_nets mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_STOPSTATE]


connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_dphy_0/inst/inst/bd_7e2a_mipi_dphy_0_0_tx_support_i/master_tx.bd_7e2a_mipi_dphy_0_0_tx67_hssio_i/inst/top_inst/clk_rst_top_inst/clk_scheme_inst/pll0_clkout0_out]]
connect_debug_port u_ila_0/probe0 [get_nets [list {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[0]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[1]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[2]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[3]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[4]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[5]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[6]} {mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXDATAHS[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_ENABLE]]
connect_debug_port u_ila_0/probe2 [get_nets [list mipi_block_top_i/mipi_csi2_tx_subsyst_0/inst/mipi_csi2_tx_ctrl_0_tx_mipi_ppi_if_DL0_TXREQUESTHS]]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rx_div4_clk]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy/inst/inst/bd_782c_phy_0_rx_support_i/rxbyteclkhs]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]} {mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_RXVALIDHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_RXVALIDHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_RXVALIDHS]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mipi_block_top_i/clk_wiz_0/inst/dphy]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL0_STOPSTATE]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL1_STOPSTATE]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL2_STOPSTATE]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list mipi_block_top_i/mipi_csi2_rx_subsyst_0/inst/phy_rx_mipi_ppi_if_DL3_STOPSTATE]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
