# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/mipi_block_top.bd
# Block Designs: The module: 'mipi_block_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_782c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c || ORIG_REF_NAME==bd_782c} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_782c_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_xbar_0 || ORIG_REF_NAME==bd_782c_xbar_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_rx_0 || ORIG_REF_NAME==bd_782c_rx_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_clock_module_rx || ORIG_REF_NAME==bd_782c_phy_0_clock_module_rx} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_hssio_rx || ORIG_REF_NAME==bd_782c_phy_0_hssio_rx} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/bd_782c_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0 || ORIG_REF_NAME==bd_782c_vfb_0_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_0/bd_782c_vfb_0_0_axis_converter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_782c_vfb_0_0_axis_converter} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_1/bd_782c_vfb_0_0_axisswitch.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_782c_vfb_0_0_axisswitch} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_2/bd_782c_vfb_0_0_sli.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_sli || ORIG_REF_NAME==bd_782c_vfb_0_0_sli} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_3/bd_782c_vfb_0_0_slo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_slo || ORIG_REF_NAME==bd_782c_vfb_0_0_slo} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/mipi_block_top_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_jtag_axi_0_0 || ORIG_REF_NAME==mipi_block_top_jtag_axi_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_axi_traffic_gen_0_0/mipi_block_top_axi_traffic_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_axi_traffic_gen_0_0 || ORIG_REF_NAME==mipi_block_top_axi_traffic_gen_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/mipi_block_top_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_smartconnect_0_0 || ORIG_REF_NAME==mipi_block_top_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/bd_b9b5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_0/bd_b9b5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_2/bd_b9b5_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_3/bd_b9b5_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_4/bd_b9b5_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_5/bd_b9b5_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_6/bd_b9b5_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_7/bd_b9b5_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_8/bd_b9b5_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_9/bd_b9b5_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_10/bd_b9b5_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_11/bd_b9b5_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_17/bd_b9b5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_18/bd_b9b5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_19/bd_b9b5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_20/bd_b9b5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_26/bd_b9b5_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_27/bd_b9b5_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_28/bd_b9b5_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_29/bd_b9b5_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_33/bd_b9b5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_39/bd_b9b5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_vio_0_1/mipi_block_top_vio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_vio_0_1 || ORIG_REF_NAME==mipi_block_top_vio_0_1} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/mipi_block_top_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_system_ila_0_1 || ORIG_REF_NAME==mipi_block_top_system_ila_0_1} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/bd_f513.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f513 || ORIG_REF_NAME==bd_f513} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/bd_f513_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_oddr_0_0/mipi_block_top_oddr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_oddr_0_0 || ORIG_REF_NAME==mipi_block_top_oddr_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_top_0_0/mipi_block_top_mipi_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_top_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_top_0_0} -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_rx_0 || ORIG_REF_NAME==bd_782c_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0_fixed_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_clock_module_rx || ORIG_REF_NAME==bd_782c_phy_0_clock_module_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_hssio_rx || ORIG_REF_NAME==bd_782c_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_1/bd_782c_vfb_0_0_axisswitch_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_782c_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/constraints/jtag_axi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_jtag_axi_0_0 || ORIG_REF_NAME==mipi_block_top_jtag_axi_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_2/bd_b9b5_arinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_3/bd_b9b5_rinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_4/bd_b9b5_awinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_5/bd_b9b5_winsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_6/bd_b9b5_binsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_7/bd_b9b5_aroutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_8/bd_b9b5_routsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_9/bd_b9b5_awoutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_10/bd_b9b5_woutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_11/bd_b9b5_boutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_20/bd_b9b5_s00a2s_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_29/bd_b9b5_s01a2s_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_33/bd_b9b5_m00s2a_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_smartconnect_0_0 || ORIG_REF_NAME==mipi_block_top_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_vio_0_1/mipi_block_top_vio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_vio_0_1 || ORIG_REF_NAME==mipi_block_top_vio_0_1} -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/bd_f513_ila_lib_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/bd_f513_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/mipi_block_top_system_ila_0_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_block_top'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/mipi_block_top.bd
# Block Designs: The module: 'mipi_block_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_782c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c || ORIG_REF_NAME==bd_782c} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_782c_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_xbar_0 || ORIG_REF_NAME==bd_782c_xbar_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_rx_0 || ORIG_REF_NAME==bd_782c_rx_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_clock_module_rx || ORIG_REF_NAME==bd_782c_phy_0_clock_module_rx} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_hssio_rx || ORIG_REF_NAME==bd_782c_phy_0_hssio_rx} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/bd_782c_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0 || ORIG_REF_NAME==bd_782c_vfb_0_0} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_0/bd_782c_vfb_0_0_axis_converter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_782c_vfb_0_0_axis_converter} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_1/bd_782c_vfb_0_0_axisswitch.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_782c_vfb_0_0_axisswitch} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_2/bd_782c_vfb_0_0_sli.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_sli || ORIG_REF_NAME==bd_782c_vfb_0_0_sli} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_3/bd_782c_vfb_0_0_slo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_782c_vfb_0_0_slo || ORIG_REF_NAME==bd_782c_vfb_0_0_slo} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/mipi_block_top_jtag_axi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_jtag_axi_0_0 || ORIG_REF_NAME==mipi_block_top_jtag_axi_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_axi_traffic_gen_0_0/mipi_block_top_axi_traffic_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_axi_traffic_gen_0_0 || ORIG_REF_NAME==mipi_block_top_axi_traffic_gen_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/mipi_block_top_smartconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_smartconnect_0_0 || ORIG_REF_NAME==mipi_block_top_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/bd_b9b5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_0/bd_b9b5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_2/bd_b9b5_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_3/bd_b9b5_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_4/bd_b9b5_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_5/bd_b9b5_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_6/bd_b9b5_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_7/bd_b9b5_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_8/bd_b9b5_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_9/bd_b9b5_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_10/bd_b9b5_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_11/bd_b9b5_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_17/bd_b9b5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_18/bd_b9b5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_19/bd_b9b5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_20/bd_b9b5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_26/bd_b9b5_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_27/bd_b9b5_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_28/bd_b9b5_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_29/bd_b9b5_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_33/bd_b9b5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_39/bd_b9b5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_vio_0_1/mipi_block_top_vio_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_vio_0_1 || ORIG_REF_NAME==mipi_block_top_vio_0_1} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/mipi_block_top_system_ila_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_system_ila_0_1 || ORIG_REF_NAME==mipi_block_top_system_ila_0_1} -quiet] -quiet

# Block Designs: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/bd_f513.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f513 || ORIG_REF_NAME==bd_f513} -quiet] -quiet

# IP: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/bd_f513_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_oddr_0_0/mipi_block_top_oddr_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_oddr_0_0 || ORIG_REF_NAME==mipi_block_top_oddr_0_0} -quiet] -quiet

# IP: C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_top_0_0/mipi_block_top_mipi_top_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_top_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_top_0_0} -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_clk_wiz_0_0 || ORIG_REF_NAME==mipi_block_top_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_r_sync_0 || ORIG_REF_NAME==bd_782c_r_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_vfb_sync_0 || ORIG_REF_NAME==bd_782c_vfb_sync_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_rx_0 || ORIG_REF_NAME==bd_782c_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0_fixed_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_clock_module_rx || ORIG_REF_NAME==bd_782c_phy_0_clock_module_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0_hssio_rx || ORIG_REF_NAME==bd_782c_phy_0_hssio_rx} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_782c_phy_0 || ORIG_REF_NAME==bd_782c_phy_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_1/bd_782c_vfb_0_0_axisswitch_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_782c_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==mipi_block_top_mipi_csi2_rx_subsyst_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_0_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_proc_sys_reset_1_0 || ORIG_REF_NAME==mipi_block_top_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/constraints/jtag_axi.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_jtag_axi_0_0 || ORIG_REF_NAME==mipi_block_top_jtag_axi_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_2/bd_b9b5_arinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_3/bd_b9b5_rinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_4/bd_b9b5_awinsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_5/bd_b9b5_winsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_6/bd_b9b5_binsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_7/bd_b9b5_aroutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_8/bd_b9b5_routsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_9/bd_b9b5_awoutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_10/bd_b9b5_woutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_11/bd_b9b5_boutsw_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_20/bd_b9b5_s00a2s_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_29/bd_b9b5_s01a2s_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_33/bd_b9b5_m00s2a_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/smartconnect.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_block_top_smartconnect_0_0 || ORIG_REF_NAME==mipi_block_top_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_vio_0_1/mipi_block_top_vio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mipi_block_top_vio_0_1 || ORIG_REF_NAME==mipi_block_top_vio_0_1} -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f513_ila_lib_0 || ORIG_REF_NAME==bd_f513_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/bd_f513_ila_lib_0_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/bd_f513_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/mipi_block_top_system_ila_0_1_ooc.xdc

# XDC: c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipi_block_top'. Do not add the DONT_TOUCH constraint.
