# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.runs/mipi_block_top_synth_1/mipi_block_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "mipi_block_top_synth_1" START { ROLLUP_AUTO }
set_param tcl.statsThreshold 360
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcau25p-ffvb676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/Al-YeeTan/AppData/Roaming/Xilinx/Vivado/2023.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part opalkelly.com:xem8320-au25p:part0:1.2 [current_project]
set_property ip_repo_paths c:/Users/Al-YeeTan/Downloads/FrontPanel-Vivado-IP-Dist-v1.0.3/FrontPanel-Vivado-IP-Dist-v1.0.3 [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/imports/Ti180M484_devkit/lfsr.v}
  {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/imports/Ti180M484_devkit/pattern_gen.v}
  {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/imports/Ti180M484_devkit/pattern_gen2.v}
  {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/imports/Ti180M484_devkit/reset.v}
  {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/new/mipi_top_pat.v}
}
add_files {{C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.srcs/sources_1/bd/mipi_block_top/mipi_block_top.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_clk_wiz_0_0/mipi_block_top_clk_wiz_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_782c_r_sync_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_782c_vfb_sync_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_782c_rx_0_fixed_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_0/bd_782c_phy_0_clock_module_rx_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/ip_1/bd_782c_phy_0_hssio_rx_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_4/bd_782c_phy_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_5/ip_1/bd_782c_vfb_0_0_axisswitch_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/bd_0/bd_782c_ooc.xdc}}]
set_property used_in_synthesis false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_mipi_csi2_rx_subsyst_0_0/mipi_block_top_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_0_0/mipi_block_top_proc_sys_reset_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_proc_sys_reset_1_0/mipi_block_top_proc_sys_reset_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/constraints/jtag_axi.xdc}}]
set_property used_in_synthesis false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/constraints/mipi_block_top_jtag_axi_0_0_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_jtag_axi_0_0/constraints/mipi_block_top_jtag_axi_0_0_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_1/bd_b9b5_psr_aclk_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_2/bd_b9b5_arinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_3/bd_b9b5_rinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_4/bd_b9b5_awinsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_5/bd_b9b5_winsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_6/bd_b9b5_binsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_7/bd_b9b5_aroutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_8/bd_b9b5_routsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_9/bd_b9b5_awoutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_10/bd_b9b5_woutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_11/bd_b9b5_boutsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_12/bd_b9b5_arni_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_13/bd_b9b5_rni_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_14/bd_b9b5_awni_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_15/bd_b9b5_wni_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_16/bd_b9b5_bni_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_20/bd_b9b5_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_21/bd_b9b5_sarn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_22/bd_b9b5_srn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_23/bd_b9b5_sawn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_24/bd_b9b5_swn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_25/bd_b9b5_sbn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_29/bd_b9b5_s01a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_30/bd_b9b5_sawn_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_31/bd_b9b5_swn_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_32/bd_b9b5_sbn_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_33/bd_b9b5_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_34/bd_b9b5_m00arn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_35/bd_b9b5_m00rn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_36/bd_b9b5_m00awn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_37/bd_b9b5_m00wn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/bd_0/ip/ip_38/bd_b9b5_m00bn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_smartconnect_0_0/smartconnect.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_vio_0_1/mipi_block_top_vio_0_1.xdc}}]
set_property used_in_synthesis false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/ip/ip_0/bd_f513_ila_lib_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/bd_0/bd_f513_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/ip/mipi_block_top_system_ila_0_1/mipi_block_top_system_ila_0_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mipi_block_top -part xcau25p-ffvb676-2-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all mipi_block_top_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mipi_block_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "mipi_block_top_synth_1_synth_report_utilization_0" "report_utilization -file mipi_block_top_utilization_synth.rpt -pb mipi_block_top_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.runs/mipi_block_top_synth_1/mipi_block_top.dcp} {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.ip_user_files/bd/mipi_block_top}]} {
  catch { 
    file copy -force {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_stub.v}} {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.ip_user_files/bd/mipi_block_top}
  }
}

if {[file isdir {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.ip_user_files/bd/mipi_block_top}]} {
  catch { 
    file copy -force {{c:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.gen/sources_1/bd/mipi_block_top/mipi_block_top_stub.vhdl}} {C:/Users/Al-YeeTan/Desktop/CSI 2.5G MIPI/au25p_mipi_csi_2-5g/MIPI_loopback_2-5g.ip_user_files/bd/mipi_block_top}
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "mipi_block_top_synth_1" END { }
